# Generated by Django 5.0.13 on 2025-09-11 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('bike_type', models.CharField(choices=[('road', 'Road'), ('mountain', 'Mountain'), ('electric', 'Electric')], default='electric', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('battery_level', models.IntegerField(blank=True, default=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('mileage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Scooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('battery_level', models.IntegerField(default=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('mileage', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.scooter')),
            ],
        ),
    ]
